export const CHARACTERS = [
  {
    id: "albedo",
    name: "Albedo",
    star: 5,
    weaponType: "Sword",
    element: "Geo",
    region: "Mon",
  },
  {
    id: "alhaitham",
    name: "Alhaitham",
    star: 5,
    weaponType: "Sword",
    element: "Dendro",
    region: "Sum",
  },
  {
    id: "aloy",
    name: "Aloy",
    star: 5,
    weaponType: "Bow",
    element: "Cryo",
    region: "Mon",
  },
  {
    id: "amber",
    name: "Amber",
    star: 4,
    weaponType: "Bow",
    element: "Pyro",
    region: "Mon",
  },
  {
    id: "ayaka",
    name: "Ayaka",
    star: 5,
    weaponType: "Sword",
    element: "Cryo",
    region: "Ina",
  },
  {
    id: "ayato",
    name: "Ayato",
    star: 5,
    weaponType: "Sword",
    element: "Hydro",
    region: "Ina",
  },
  {
    id: "baizhu",
    name: "Baizhu",
    star: 5,
    weaponType: "Catalyst",
    element: "Dendro",
    region: "Ly",
  },
  {
    id: "barbara",
    name: "Barbara",
    star: 4,
    weaponType: "Catalyst",
    element: "Hydro",
    region: "Mon",
  },
  {
    id: "beidou",
    name: "Beidou",
    star: 4,
    weaponType: "Claymore",
    element: "Electro",
    region: "Ly",
  },
  {
    id: "bennett",
    name: "Bennett",
    star: 4,
    weaponType: "Sword",
    element: "Pyro",
    region: "Mon",
  },
  {
    id: "candace",
    name: "Candace",
    star: 4,
    weaponType: "Polearm",
    element: "Hydro",
    region: "Sum",
  },
  {
    id: "charlotte",
    name: "Charlotte",
    star: 4,
    weaponType: "Cataylst",
    element: "Cryo",
    region: "Fon",
  },
  {
    id: "chevreuse",
    name: "Chevreuse",
    star: 4,
    weaponType: "Polearm",
    element: "Pyro",
    region: "Fon",
  },
  {
    id: "chiori",
    name: "Chiori",
    star: 5,
    weaponType: "Polearm",
    element: "Geo",
    region: "Fon",
  },
  {
    id: "chongyun",
    name: "Chongyun",
    star: 4,
    weaponType: "Claymore",
    element: "Cryo",
    region: "Ly",
  },
  {
    id: "collei",
    name: "Collei",
    star: 4,
    weaponType: "Bow",
    element: "Dendro",
    region: "Sum",
  },
  {
    id: "cyno",
    name: "Cyno",
    star: 5,
    weaponType: "Polearm",
    element: "Electro",
    region: "Sum",
  },
  {
    id: "dehya",
    name: "Dehya",
    star: 5,
    weaponType: "Claaymore",
    element: "Pyro",
    region: "Sum",
  },
  {
    id: "diluc",
    name: "Diluc",
    star: 5,
    weaponType: "Claymore",
    element: "Pyro",
    region: "Mon",
  },
  {
    id: "diona",
    name: "Diona",
    star: 4,
    weaponType: "Bow",
    element: "Cryo",
    region: "Mon",
  },
  {
    id: "dori",
    name: "Dori",
    star: 4,
    weaponType: "Claymore",
    element: "Electro",
    region: "Sum",
  },
  {
    id: "eula",
    name: "Eula",
    star: 5,
    weaponType: "Claymore",
    element: "Cryo",
    region: "Mon",
  },
  {
    id: "faruzan",
    name: "Faruzan",
    star: 4,
    weaponType: "Bow",
    element: "Anemo",
    region: "Sum",
  },
  {
    id: "fischl",
    name: "Fischl",
    star: 4,
    weaponType: "Bow",
    element: "Electro",
    region: "Mon",
  },
  {
    id: "freminet",
    name: "Freminet",
    star: 4,
    weaponType: "Claymore",
    element: "Cryo",
    region: "Fon",
  },
  {
    id: "furina",
    name: "Furina",
    star: 5,
    weaponType: "Sword",
    element: "Hydro",
    region: "Fon",
  },
  {
    id: "gaming",
    name: "Gaming",
    star: 4,
    weaponType: "Claymore",
    element: "Pyro",
    region: "Fon",
  },
  {
    id: "ganyu",
    name: "Ganyu",
    star: 5,
    weaponType: "Bow",
    element: "Cryo",
    region: "Ly",
  },
  {
    id: "gorou",
    name: "Gorou",
    star: 4,
    weaponType: "Bow",
    element: "Geo",
    region: "Ina",
  },
  {
    id: "heizou",
    name: "Heizou",
    star: 4,
    weaponType: "Cataylst",
    element: "Anemo",
    region: "Ina",
  },
  {
    id: "hutao",
    name: "Hu tao",
    star: 5,
    weaponType: "Polearm",
    element: "Pyro",
    region: "Ly",
  },
  {
    id: "itto",
    name: "Itto",
    star: 5,
    weaponType: "Claymore",
    element: "Geo",
    region: "Ina",
  },
  {
    id: "jean",
    name: "Jean",
    star: 5,
    weaponType: "Sword",
    element: "Anemo",
    region: "Mon",
  },
  {
    id: "kaeya",
    name: "Kaeya",
    star: 4,
    weaponType: "Sword",
    element: "Cryo",
    region: "Mon",
  },
  {
    id: "kaveh",
    name: "Kaveh",
    star: 4,
    weaponType: "Claaymore",
    element: "Dendro",
    region: "Sum",
  },
  {
    id: "kazuha",
    name: "Kazuha",
    star: 5,
    weaponType: "Sword",
    element: "Anemo",
    region: "Ina",
  },
  {
    id: "keqing",
    name: "Keqing",
    star: 5,
    weaponType: "Sword",
    element: "Electro",
    region: "Ly",
  },
  {
    id: "kirara",
    name: "Kirara",
    star: 4,
    weaponType: "Sword",
    element: "Dendro",
    region: "Ina",
  },
  {
    id: "klee",
    name: "Klee",
    star: 5,
    weaponType: "Catalyst",
    element: "Pyro",
    region: "Mon",
  },
  {
    id: "kokomi",
    name: "Kokomi",
    star: 5,
    weaponType: "Catalyst",
    element: "Hydro",
    region: "Ina",
  },
  {
    id: "kuki",
    name: "Kuki",
    star: 4,
    weaponType: "Sword",
    element: "Electro",
    region: "Ina",
  },
  {
    id: "layla",
    name: "Layla",
    star: 4,
    weaponType: "Sword",
    element: "Cryo",
    region: "Sum",
  },
  {
    id: "lisa",
    name: "Lisa",
    star: 4,
    weaponType: "Cataylst",
    element: "Electro",
    region: "Mon",
  },
  {
    id: "lynette",
    name: "Linette",
    star: 4,
    weaponType: "Sword",
    element: "Anemo",
    region: "Fon",
  },
  {
    id: "lyney",
    name: "Liney",
    star: 5,
    weaponType: "Bow",
    element: "Pyro",
    region: "Fon",
  },
  {
    id: "mika",
    name: "Mika",
    star: 4,
    weaponType: "Polearm",
    element: "Cryo",
    region: "Mon",
  },
  {
    id: "mona",
    name: "Mona",
    star: 5,
    weaponType: "Cataylst",
    element: "Hydro",
    region: "Mon",
  },
  {
    id: "nahida",
    name: "Nahida",
    star: 5,
    weaponType: "Cataylst",
    element: "Denro",
    region: "Sum",
  },
  {
    id: "navia",
    name: "Navia",
    star: 5,
    weaponType: "Claaymore",
    element: "Geo",
    region: "Fon",
  },
  {
    id: "neuvillette",
    name: "Neuvillette",
    star: 5,
    weaponType: "Cataylst",
    element: "Hydro",
    region: "Fon",
  },
  {
    id: "nilou",
    name: "Nilou",
    star: 5,
    weaponType: "Sword",
    element: "Hydro",
    region: "Sum",
  },
  {
    id: "ningguang",
    name: "Ningguang",
    star: 4,
    weaponType: "Cataylst",
    element: "Geo",
    region: "Ly",
  },
  {
    id: "noelle",
    name: "Noelle",
    star: 4,
    weaponType: "Claymore",
    element: "Geo",
    region: "Mon",
  },
  {
    id: "qiqi",
    name: "Qiqi",
    star: 5,
    weaponType: "Sword",
    element: "Cryo",
    region: "Mon",
  },
  {
    id: "raiden",
    name: "Raiden",
    star: 5,
    weaponType: "Polearm",
    element: "Electro",
    region: "Ina",
  },
  {
    id: "razor",
    name: "Razor",
    star: 4,
    weaponType: "Claymore",
    element: "Electro",
    region: "Mon",
  },
  {
    id: "rosaria",
    name: "Rosaria",
    star: 4,
    weaponType: "Polearm",
    element: "Cryo",
    region: "Mon",
  },
  {
    id: "sara",
    name: "Sara",
    star: 4,
    weaponType: "Bow",
    element: "Electro",
    region: "Ina",
  },
  {
    id: "sayu",
    name: "Sayu",
    star: 4,
    weaponType: "Claymore",
    element: "Anemo",
    region: "Ina",
  },
  {
    id: "shenhe",
    name: "Shenhe",
    star: 5,
    weaponType: "Polearm",
    element: "Cryo",
    region: "Ly",
  },
  {
    id: "sucrose",
    name: "Sucrose",
    star: 4,
    weaponType: "Cataylst",
    element: "Anemo",
    region: "Mon",
  },
  {
    id: "tartaglia",
    name: "Tartaglia",
    star: 5,
    weaponType: "Bow",
    element: "Hydro",
    region: "Sne",
  },
  {
    id: "thoma",
    name: "Thoma",
    star: 4,
    weaponType: "Polearm",
    element: "Pyro",
    region: "Ina",
  },
  {
    id: "tighnari",
    name: "Tighnari",
    star: 5,
    weaponType: "Bow",
    element: "Dendro",
    region: "Sum",
  },
  {
    id: "traveler",
    name: "Traveler",
    star: 5,
    weaponType: "Sword",
    element: "Anemo",
    region: "Mon",
  },
  {
    id: "venti",
    name: "Venti",
    star: 5,
    weaponType: "Bow",
    element: "Anemo",
    region: "Mon",
  },
  {
    id: "wanderer",
    name: "Wanderer",
    star: 5,
    weaponType: "Cataylst",
    element: "Anemo",
    region: "Sum",
  },
  {
    id: "wriothesley",
    name: "Wriothesley",
    star: 5,
    weaponType: "Cataylst",
    element: "Cryo",
    region: "Fon",
  },
  {
    id: "xiangling",
    name: "Xiangling",
    star: 4,
    weaponType: "Polearm",
    element: "Pyro",
    region: "Ly",
  },
  {
    id: "xianyun",
    name: "Xianyun",
    star: 5,
    weaponType: "Cataylst",
    element: "Anemo",
    region: "Ly",
  },
  {
    id: "xiao",
    name: "Xiao",
    star: 5,
    weaponType: "Polearm",
    element: "Anemo",
    region: "Ly",
  },
  {
    id: "xingqiu",
    name: "Xingqiu",
    star: 4,
    weaponType: "Sword",
    element: "Hydro",
    region: "Ly",
  },
  {
    id: "xinyan",
    name: "Xinyan",
    star: 4,
    weaponType: "Claymore",
    element: "Pyro",
    region: "Ly",
  },
  {
    id: "yaemiko",
    name: "Yae miko",
    star: 5,
    weaponType: "Cataylst",
    element: "Electro",
    region: "Ina",
  },
  {
    id: "yanfei",
    name: "Yanfei",
    star: 4,
    weaponType: "Cataylst",
    element: "Pyro",
    region: "Ly",
  },
  {
    id: "yaoyao",
    name: "Yaoyao",
    star: 4,
    weaponType: "Polarm",
    element: "Dendro",
    region: "Ly",
  },
  {
    id: "yelan",
    name: "Yelan",
    star: 5,
    weaponType: "Bow",
    element: "Hydro",
    region: "Ly",
  },
  {
    id: "yoimiya",
    name: "Yoimiya",
    star: 5,
    weaponType: "Bow",
    element: "Pyro",
    region: "Ina",
  },
  {
    id: "zhongli",
    name: "Zhongli",
    star: 5,
    weaponType: "Polearm",
    element: "Geo",
    region: "Ly",
  },
] as const;
